; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini_lite]
platform = espressif8266
board = d1_mini_lite
framework = arduino
monitor_speed = 74880
board_build.flash_mode = dio
; upload_resetmethod = nodemcu
upload_speed = 115200 
board_build.filesystem = littlefs
lib_deps =
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    ayushsharma82/AsyncElegantOTA @ ^2.2.8

[env:d1_mini_lite_ota]
platform = espressif8266
board = d1_mini_lite
framework = arduino
monitor_speed = 74880
board_build.flash_mode = dio
upload_protocol = espota
; upload_resetmethod = nodemcu
upload_speed = 115200 
upload_port = 10.11.85.65
upload_flags =
  --port=8266
  --auth=admin
lib_deps = 
  ESP8266WiFi @ ^1.0
  ottowinter/ESPAsyncWebServer-esphome @ ^1.2.7
  ottowinter/ESPAsyncTCP-esphome @ ^1.2.3
